spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bgm?createDatabaseIfNotExist=true
    username: root
    password: 1qazxsw2#EDCVFR$
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
        format_sql: true
    hibernate:
      generate-ddl: true
      ddl-auto: update
    open-in-view: false